### ISSUE TITLE
Socks5 通信优化项（进一步提高 lproxy 的性能）

### ISSUE THREAD

**Issue by DD-L** [DD-L/lproxy#127]
版本：v0.1.0.20160418_Beta

lss 握手以后，就开始转发 Socks5 数据了，在 Socks5 刚开始的阶段：

socks5-client -> socks5-server

| VER | NMETHODS | METHODS |
| --- | --- | --- |
| 1 | 1 | 1 to 255 |

然后 socks5-server -> socks5-client 应答

| VER | METHOD |
| --- | --- |
| 1 | 1 |

这一应答过程，在 v0.1.0.20160418_Beta 版本中是通过 lssserver 端完成的，其实完全没有这个必要，这一步完全可以在 lsslocal 端完成。这样优化的话有很多好处：
1. 减少 lsslocal 和 lssserver 之间的请求应答次数，进而节省宽带，提高网络利用率。
2. 减轻 lssserver 端的负担，如果并发比较多，那减的负担可不是一丁点了，使 lssserver 抽开身完成其他待处理的工作。

总之，性能会进一步提高

**Comment by DD-L** [comment]
已经在即将发布的 `v0.2.0` 版本中实现

**Comment by DD-L** [comment]
`v0.2.0.20160429_Beta` 已经发布 https://github.com/DD-L/lproxy/releases/tag/0.2.0.20160429_Beta

**Comment by gujiejie** [comment]
2.0. 的转发效率是比ss高 比较明显
